language:
  - python

python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install flake8

script:
  - flake8 rss-generator.py
  - py.test rss-generator.py
  - py.test --cov

after_success:
  - coveralls